# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x0fwally.telemetry\"+\n\x10SubscribeRequest\x12\x17\n\x0flast_message_id\x18\x01 \x01(\x03\"b\n\x11TelemetryResponse\x12\x10\n\x08strategy\x18\x01 \x01(\t\x12\x11\n\tserved_at\x18\x02 \x01(\x03\x12(\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x1a.wally.telemetry.RobotData\"\xcb\x01\n\tRobotData\x12\x12\n\nmessage_id\x18\x01 \x01(\x03\x12\x10\n\x08robot_id\x18\x02 \x01(\t\x12\x18\n\x10server_timestamp\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x15\n\rbricks_placed\x18\x05 \x01(\x03\x12\x19\n\x11\x62ricks_per_minute\x18\x06 \x01(\x01\x12\x12\n\nerror_code\x18\x07 \x01(\t\x12\x14\n\x0cglue_quality\x18\x08 \x01(\x01\x12\x12\n\ncreated_at\x18\t \x01(\x03\x32n\n\x10TelemetryService\x12Z\n\x0fStreamTelemetry\x12!.wally.telemetry.SubscribeRequest\x1a\".wally.telemetry.TelemetryResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBEREQUEST']._serialized_start=36
  _globals['_SUBSCRIBEREQUEST']._serialized_end=79
  _globals['_TELEMETRYRESPONSE']._serialized_start=81
  _globals['_TELEMETRYRESPONSE']._serialized_end=179
  _globals['_ROBOTDATA']._serialized_start=182
  _globals['_ROBOTDATA']._serialized_end=385
  _globals['_TELEMETRYSERVICE']._serialized_start=387
  _globals['_TELEMETRYSERVICE']._serialized_end=497
# @@protoc_insertion_point(module_scope)
